/*
This file is automatically generated
times_12_L2
C Source
*/

#include "App_Common.h"

#define FONT_HANDLE       (1)
#define FONT_FILE_ADDRESS (RAM_G + 1000)
#define STRIDE            (3)
#define FONT_WIDTH        (12)
#define FONT_HEIGHT       (14)
#define FIRST_CHARACTER   (32)

void Load_Font()
{
	Gpu_CoCmd_Dlstart(phost);
	App_WrCoCmd_Buffer(phost, CLEAR(1, 1, 1));
	App_WrCoCmd_Buffer(phost, COLOR_RGB(255, 255, 255));
	Gpu_Hal_LoadImageToMemory(phost, "path\\to\\times_12_L2.raw", FONT_FILE_ADDRESS, LOAD);

	App_WrCoCmd_Buffer(phost, BITMAP_HANDLE(FONT_HANDLE));
	App_WrCoCmd_Buffer(phost, BITMAP_SOURCE(FONT_FILE_ADDRESS + 148 - STRIDE*FONT_HEIGHT*FIRST_CHARACTER));
	App_WrCoCmd_Buffer(phost, BITMAP_LAYOUT(L2, STRIDE, FONT_HEIGHT));
	App_WrCoCmd_Buffer(phost, BITMAP_SIZE(NEAREST, BORDER, BORDER, FONT_WIDTH, FONT_HEIGHT));
	Gpu_CoCmd_SetFont(phost, FONT_HANDLE, FONT_FILE_ADDRESS);
	Gpu_CoCmd_Text(phost, 0, 0, FONT_HANDLE, 0, "AaBbCcDdEeFf");
	App_WrCoCmd_Buffer(phost, DISPLAY());
	Gpu_CoCmd_Swap(phost);
	App_Flush_Co_Buffer(phost);
	Gpu_Hal_WaitCmdfifo_empty(phost);
}

/* end of file */
